# Generated by Django 5.2.7 on 2025-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_gmina_rodzaj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmina",
            name="minimalne_naklady",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimalne nakłady inwestycyjne w złotych",
                max_digits=12,
                null=True,
                verbose_name="Minimalne nakłady (PLN)",
            ),
        ),
    ]
