# Generated by Django 5.2.7 on 2025-11-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_gmina_strefa_ekonomiczna"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artykul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="URL (slug)",
                    ),
                ),
                (
                    "lead",
                    models.TextField(max_length=300, verbose_name="Krótki opis (lead)"),
                ),
                ("tresc", models.TextField(verbose_name="Treść artykułu")),
                (
                    "data_publikacji",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data publikacji"
                    ),
                ),
                (
                    "data_aktualizacji",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aktualizacji"
                    ),
                ),
                (
                    "opublikowany",
                    models.BooleanField(default=True, verbose_name="Opublikowany"),
                ),
            ],
            options={
                "verbose_name": "Artykuł",
                "verbose_name_plural": "Artykuły",
                "ordering": ["-data_publikacji"],
            },
        ),
    ]
