# Generated by Django 5.2.7 on 2025-11-13 08:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_artykul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='tresc',
            field=tinymce.models.HTMLField(verbose_name='Treść artykułu'),
        ),
    ]
